In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = 'https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/course_lead_scoring_2026.csv'

!wget $data -O course_lead_scoring_2026.csv

--2026-10-11 23:09:47--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/course_lead_scoring_2026.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 278746 (272K) [text/plain]
Saving to: ‘course_lead_scoring_2026.csv’

course_lead_scoring 100%[===================>] 272.21K  1.19MB/s    in 0.2s

2026-10-11 23:09:48 (1.19 MB/s) - ‘course_lead_scoring_2026.csv’ saved [278746/278746]

In [3]:
df = pd.read_csv('course_lead_scoring_2026.csv')
df.head()

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NaN,NaN,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1

In [4]:
df.columns

Index(['lead_source', 'industry', 'employment_status', 'location',
       'annual_income', 'number_of_courses_viewed', 'interaction_count',
       'lead_score', 'converted'],
      dtype='str')

In [5]:
df.dtypes

lead_source                     str
industry                        str
employment_status               str
location                        str
annual_income               float64
number_of_courses_viewed      int64
interaction_count             int64
lead_score                  float64
converted                     int64
dtype: object

In [6]:
df.isnull().sum()

lead_source                 148
industry                    240
employment_status           194
location                    208
annual_income               369
number_of_courses_viewed      0
interaction_count             0
lead_score                   35
converted                     0
dtype: int64

In [7]:
df.dtypes == 'str'

lead_source                  True
industry                     True
employment_status            True
location                     True
annual_income               False
number_of_courses_viewed    False
interaction_count           False
lead_score                  False
converted                   False
dtype: bool

In [8]:
categorical = ['lead_source','industry','employment_status','location']

In [9]:
numerical = ['annual_income','number_of_courses_viewed','interaction_count','lead_score']

In [10]:
df[:20]

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NaN,NaN,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1
5,referral,manufacturing,employed,africa,43841.0,3,5,0.77,1
6,NaN,education,employed,north_america,58738.0,3,9,0.78,1
7,paid_ads,technology,employed,north_america,95059.0,2,4,0.41,1
8,organic_search,healthcare,employed,asia,62565.0,3,6,0.52,1
9,referral,retail,student,asia,12000.0,2,2,0.35,0
10,referral,retail,NaN,europe,43935.0,2,9,0.78,1
11,paid_ads,technology,employed,asia,80773.0,3,7,0.72,1
12,social_media,NaN,employed,africa,47115.0,1,0,0.11,0
13,paid_ads,retail,employed,north_america,62439.0,1,2,0.33,0
14,paid_ads,retail,student,asia,12000.0,0,1,0.13,0
15,organic_search,retail,employed,north_america,59239.0,3,9,0.85,1
16,organic_search,education,employed,asia,37431.0,3,5,0.55,0
17,organic_search,finance,employed,north_america,83331.0,3,5,0.56,1
18,referral,manufacturing,employed,africa,49038.0,2,3,0.50,1
19,social_media,finance,unemployed,asia,50544.0,2,2,0.40,1

In [11]:
df.head

<bound method NDFrame.head of          lead_source       industry employment_status       location  \
0     organic_search     technology          employed         europe
1       social_media     technology          employed  south_america
2           referral         retail          employed         europe
3           paid_ads  manufacturing           student            NaN
4           referral  manufacturing           student  north_america
...              ...            ...               ...            ...
4995  organic_search      education          employed           asia
4996             NaN     technology          employed  north_america
4997  organic_search        finance          employed           asia
4998        referral     technology          employed         africa
4999        referral     technology          employed         europe

      annual_income  number_of_courses_viewed  interaction_count  lead_score  \
0           88160.0                         3                  4        0.64
1           72688.0                         3                  7        0.72
2           44697.0                         3                  4        0.58
3               NaN                         3                  6        0.57
4           24062.0                         4                  5        0.62
...             ...                       ...                ...         ...
4995        45834.0                         2                  2        0.37
4996        84831.0                         2                  5        0.51
4997        53636.0                         4                  6        0.75
4998        69430.0                         4                  8        0.79
4999        81355.0                         6                 11        0.99

      converted
0             1
1             1
2             1
3             0
4             1
...         ...
4995          1
4996          0
4997          1
4998          1
4999          1

[5000 rows x 9 columns]>

In [12]:
for col in categorical:
    df[col] = df[col].fillna('NA')

In [13]:
df.head()

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NA,NaN,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1

In [14]:
for col in numerical:
    df[col] = df[col].fillna(0)

In [15]:
df[:20]

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NA,0.0,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1
5,referral,manufacturing,employed,africa,43841.0,3,5,0.77,1
6,NA,education,employed,north_america,58738.0,3,9,0.78,1
7,paid_ads,technology,employed,north_america,95059.0,2,4,0.41,1
8,organic_search,healthcare,employed,asia,62565.0,3,6,0.52,1
9,referral,retail,student,asia,12000.0,2,2,0.35,0
10,referral,retail,NA,europe,43935.0,2,9,0.78,1
11,paid_ads,technology,employed,asia,80773.0,3,7,0.72,1
12,social_media,NA,employed,africa,47115.0,1,0,0.11,0
13,paid_ads,retail,employed,north_america,62439.0,1,2,0.33,0
14,paid_ads,retail,student,asia,12000.0,0,1,0.13,0
15,organic_search,retail,employed,north_america,59239.0,3,9,0.85,1
16,organic_search,education,employed,asia,37431.0,3,5,0.55,0
17,organic_search,finance,employed,north_america,83331.0,3,5,0.56,1
18,referral,manufacturing,employed,africa,49038.0,2,3,0.50,1
19,social_media,finance,unemployed,asia,50544.0,2,2,0.40,1

In [16]:
df_group = df.groupby('industry').lead_source.agg(['count'])

In [17]:
df_group

               count
industry
NA               240
education        639
finance          720
healthcare       840
manufacturing    463
retail           925
technology      1173

In [18]:
df[numerical].head()

   annual_income  number_of_courses_viewed  interaction_count  lead_score
0        88160.0                         3                  4        0.64
1        72688.0                         3                  7        0.72
2        44697.0                         3                  4        0.58
3            0.0                         3                  6        0.57
4        24062.0                         4                  5        0.62

In [19]:
df[numerical].corrwith(df.interaction_count)

annual_income               0.122842
number_of_courses_viewed    0.721609
interaction_count           1.000000
lead_score                  0.915746
dtype: float64

In [20]:
df[numerical].corrwith(df.number_of_courses_viewed)

annual_income               0.161300
number_of_courses_viewed    1.000000
interaction_count           0.721609
lead_score                  0.757204
dtype: float64

In [21]:
df[numerical].corrwith(df.annual_income)

annual_income               1.000000
number_of_courses_viewed    0.161300
interaction_count           0.122842
lead_score                  0.229496
dtype: float64

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(
    df_full_train, test_size=0.25, random_state=42
)

In [24]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [25]:
y_train = df_train.converted.values
y_val = df_val.converted.values
y_test = df_test.converted.values

In [26]:
del df_train['converted']
del df_val['converted']
del df_test['converted']

In [27]:
from sklearn.metrics import mutual_info_score

In [28]:
categorical

['lead_source', 'industry', 'employment_status', 'location']

In [29]:
mutual_info_score(df_full_train.converted,df_full_train.lead_source)

0.0347609795100606

In [30]:
mutual_info_score(df_full_train.converted,df_full_train.industry)

0.0028984818739526547

In [31]:
mutual_info_score(df_full_train.converted,df_full_train.employment_status)

0.02031283511067701

In [32]:
mutual_info_score(df_full_train.converted,df_full_train.location)

0.0010498214288891111

In [33]:
from sklearn.feature_extraction import DictVectorizer

In [34]:
df_train[categorical].iloc[:100]

       lead_source    industry employment_status       location
0         paid_ads     finance          employed           asia
1           events     finance          employed  south_america
2         referral          NA          employed           asia
3   organic_search     finance          employed  north_america
4           events  technology          employed  north_america
..             ...         ...               ...            ...
95    social_media  healthcare     self_employed           asia
96        paid_ads  technology          employed  south_america
97    social_media  healthcare          employed  north_america
98          events      retail     self_employed  north_america
99  organic_search  healthcare           student         africa

[100 rows x 4 columns]

In [35]:
dicts = df_train[categorical].to_dict(orient='records')

In [36]:
dv = DictVectorizer(sparse=False)

In [37]:
dv.fit(dicts)

DictVectorizer(sparse=False)

In [38]:
dv.transform(dicts)

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], shape=(3000, 24))

In [39]:
train_dicts = df_train[categorical + numerical].to_dict(orient='records')

In [40]:
numerical

['annual_income',
 'number_of_courses_viewed',
 'interaction_count',
 'lead_score']

In [41]:
train_dicts[0]

{'lead_source': 'paid_ads',
 'industry': 'finance',
 'employment_status': 'employed',
 'location': 'asia',
 'annual_income': 65980.0,
 'number_of_courses_viewed': 2,
 'interaction_count': 3,
 'lead_score': 0.37}

In [42]:
dv.fit(train_dicts)

DictVectorizer(sparse=False)

In [43]:
list(dv.transform(train_dicts[:5])[0])

[np.float64(65980.0),
 np.float64(0.0),
 np.float64(1.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(1.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(3.0),
 np.float64(0.37),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(1.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(1.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(2.0)]

In [44]:
X_train = dv.transform(train_dicts)

In [45]:
X_train.shape

(3000, 28)

In [46]:
val_dicts = df_val[categorical + numerical].to_dict(orient='records')

In [47]:
X_val = dv.transform(val_dicts)

In [48]:
def sigmoid(z):
    return 1 / (1  + np.exp(-z))

In [49]:
def logistic_regression(xi):
    score = w0

    for j in range(len(w)):
        score = score + xi[j] * xi[j]
    result = sigmoid(score)
    return result

In [50]:
from sklearn.linear_model import LogisticRegression

In [51]:
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)

In [52]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [53]:
model.intercept_[0]

np.float64(-0.010838978497809069)

In [54]:
model.coef_

array([[-4.57849985e-06, -5.83434850e-04,  7.40346890e-03,
        -3.28471892e-03, -8.04069170e-03, -6.33360193e-03,
        -4.41226767e-04, -2.95759734e-03, -6.49404976e-04,
        -2.15453817e-03, -2.30751043e-03, -1.65985277e-03,
        -6.68848037e-04,  1.36728058e-01,  1.10036031e-02,
         9.51725098e-05, -8.62466509e-03,  6.94367905e-03,
        -1.37825294e-02,  8.71726672e-03, -4.18790228e-03,
         2.30545170e-04, -1.79050012e-03, -1.77472633e-03,
        -5.83764763e-04, -3.10519687e-03, -3.81533558e-03,
         5.37983416e-02]])

In [55]:
model.coef_[0].round(3)

array([-0.   , -0.001,  0.007, -0.003, -0.008, -0.006, -0.   , -0.003,
       -0.001, -0.002, -0.002, -0.002, -0.001,  0.137,  0.011,  0.   ,
       -0.009,  0.007, -0.014,  0.009, -0.004,  0.   , -0.002, -0.002,
       -0.001, -0.003, -0.004,  0.054])

In [56]:
y_pred = model.predict_proba(X_val)[:,1]

In [57]:
converted_decision = (y_pred >= 0.5)

In [58]:
y_val

array([1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 1])

In [104]:
accuracy = (y_val == converted_decision).mean()
accuracy

np.float64(0.645)

## remove lead sources

In [60]:
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)

In [61]:
categorical_no_lead_source = ['industry','employment_status','location']

In [62]:
categorical_no_lead_source

['industry', 'employment_status', 'location']

In [63]:
train_dicts_no_lead_source = df_train[categorical_no_lead_source + numerical].to_dict(orient='records')

In [64]:
train_dicts_no_lead_source[1]

{'industry': 'finance',
 'employment_status': 'employed',
 'location': 'south_america',
 'annual_income': 71662.0,
 'number_of_courses_viewed': 0,
 'interaction_count': 0,
 'lead_score': 0.09}

In [65]:
dv_no_lead_source = DictVectorizer(sparse=False)

In [66]:
X_train = dv_no_lead_source.fit_transform(train_dicts_no_lead_source)
X_train.shape

(3000, 22)

In [67]:
y_train

array([1, 0, 1, ..., 1, 0, 0], shape=(3000,))

In [68]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [69]:
val_dicts_no_lead_source = df_val[categorical_no_lead_source + numerical].to_dict(orient='records')
X_val = dv_no_lead_source.transform(val_dicts_no_lead_source)

In [70]:
X_val.shape

(1000, 22)

In [71]:
X_train.shape

(3000, 22)

In [72]:
y_pred_no_lead_source = model.predict_proba(X_val)[:,1]

y_pred_no_lead_source[:5]

array([0.61638735, 0.44345856, 0.6075418 , 0.64360473, 0.52392326])

In [73]:
converted_decision_no_lead_source = (y_pred_no_lead_source >= 0.5)
converted_decision_no_lead_source[:5]

array([ True, False,  True,  True,  True])

In [101]:
accuracy_no_lead_source = (y_val == converted_decision_no_lead_source).mean()
accuracy_no_lead_source

np.float64(0.642)

## remove courses viewed

In [75]:
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)

In [76]:
numerical

['annual_income',
 'number_of_courses_viewed',
 'interaction_count',
 'lead_score']

In [77]:
numerical_no_courses = ['annual_income',
 'interaction_count',
 'lead_score']

In [78]:
train_dicts_no_courses = df_train[categorical + numerical_no_courses].to_dict(orient='records')

In [79]:
dv.fit(train_dicts_no_courses)

DictVectorizer(sparse=False)

In [80]:
X_train = dv.transform(train_dicts_no_courses)

In [81]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [82]:
val_dicts_no_courses = df_val[categorical + numerical_no_courses].to_dict(orient='records')

In [83]:
X_val = dv.transform(val_dicts_no_courses)

In [84]:
y_pred_no_courses = model.predict_proba(X_val)[:,1]

In [85]:
converted_decision_no_courses = (y_pred_no_courses >= 0.5)

In [102]:
accuracy_no_courses = (y_val == converted_decision_no_courses).mean()
accuracy_no_courses

np.float64(0.643)

## remove interaction count

In [87]:
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)

In [88]:
numerical_no_interaction = ['annual_income','number_of_courses_viewed','lead_score']

In [89]:
categorical

['lead_source', 'industry', 'employment_status', 'location']

In [90]:
train_dicts_no_interaction = df_train[categorical + numerical_no_interaction].to_dict(orient='records')

In [91]:
dv.fit(train_dicts_no_interaction)

DictVectorizer(sparse=False)

In [92]:
X_train = dv.transform(train_dicts_no_interaction)

In [93]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [94]:
val_dicts_no_interaction = df_val[categorical + numerical_no_interaction].to_dict(orient='records')

In [95]:
X_val = dv.transform(val_dicts_no_interaction)

In [96]:
y_pred_no_interaction = model.predict_proba(X_val)[:,1]

In [97]:
converted_decision_no_interaction = (y_pred_no_interaction >= 0.5)

In [103]:
accuracy_no_interaction = (y_val == converted_decision_no_interaction).mean()
accuracy_no_interaction

np.float64(0.601)

## Question 6

In [107]:

for c in [0.000001, 0.00001, 0.0001, 0.001]:

  
    full_train_dicts = df_train[categorical + numerical].to_dict(orient='records')
    dv.fit(full_train_dicts)
    X_train = dv.transform(full_train_dicts)

    full_val_dicts = df_val[categorical + numerical].to_dict(orient='records')

    X_val = dv.transform(full_val_dicts)
    
    model = LogisticRegression(solver='liblinear', C=c, max_iter=1000, random_state=42)
    model.fit(X_train, y_train)

    full_y_pred = model.predict_proba(X_val)[:,1]
    
    full_converted_decision = (full_y_pred >= 0.5)
    full_accuracy = (y_val == full_converted_decision).mean().round(3)
    
    print(c,full_accuracy)

1e-06 0.598
1e-05 0.598
0.0001 0.613
0.001 0.645