In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
from sklearn.feature_extraction import DictVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import export_text
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import root_mean_squared_error
import xgboost as xgb

In [2]:
data =  'https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv'
!wget $data -O car_fuel_efficiency_2026.csv

--2026-10-29 18:03:03--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 635180 (620K) [text/plain]
Saving to: ‘car_fuel_efficiency_2026.csv’

car_fuel_efficiency 100%[===================>] 620.29K  --.-KB/s    in 0.06s

2026-10-29 18:03:03 (9.99 MB/s) - ‘car_fuel_efficiency_2026.csv’ saved [635180/635180]

In [3]:
df = pd.read_csv('car_fuel_efficiency_2026.csv')
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [4]:
df.dtypes

model_year               int64
origin                     str
fuel_type                  str
drivetrain                 str
num_doors                int64
engine_displacement      int64
num_cylinders            int64
horsepower             float64
vehicle_weight           int64
acceleration           float64
fuel_efficiency_mpg    float64
dtype: object

In [5]:
numerical = ['model_year','num_doors','engine_displacement','num_cylinders','horsepower','vehicle_weight','acceleration','fuel_efficiency_mpg']

In [6]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [7]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)
df_train, df_val = train_test_split(
    df_full_train, test_size=0.25, random_state=1
)

In [8]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [9]:
y_train = df_train.fuel_efficiency_mpg.values
y_val = df_val.fuel_efficiency_mpg.values
y_test = df_test.fuel_efficiency_mpg.values

In [10]:
del df_train['fuel_efficiency_mpg']
del df_val['fuel_efficiency_mpg']
del df_test['fuel_efficiency_mpg']

## Question 1

In [11]:
train_dicts = df_train.fillna(0).to_dict(orient='records')
test_dicts = df_test.fillna(0).to_dict(orient='records')
val_dicts = df_val.fillna(0).to_dict(orient='records')

dv = DictVectorizer(sparse=True)

X_train = dv.fit_transform(train_dicts)
X_test = dv.transform(test_dicts)
X_val = dv.transform(val_dicts)

In [12]:
print("Generated Features:", dv.get_feature_names_out())

Generated Features: ['acceleration' 'drivetrain=All-wheel drive'
 'drivetrain=Front-wheel drive' 'drivetrain=Rear-wheel drive'
 'engine_displacement' 'fuel_type=Diesel' 'fuel_type=Gasoline'
 'fuel_type=Hybrid' 'horsepower' 'model_year' 'num_cylinders' 'num_doors'
 'origin=Asia' 'origin=Europe' 'origin=USA' 'vehicle_weight']

In [13]:
dt = DecisionTreeRegressor(max_depth=1)
dt.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=1)

In [14]:
dv.get_feature_names_out

In [15]:
print(export_text(dt, feature_names=list(dv.get_feature_names_out())))

|--- model_year <= 1997.50
|   |--- value: [28.61]
|--- model_year >  1997.50
|   |--- value: [31.17]

## Question 2

In [16]:
rf = RandomForestRegressor(n_estimators=10,random_state=1,n_jobs=-1)
rf.fit(X_train, y_train)

RandomForestRegressor(n_estimators=10, n_jobs=-1, random_state=1)

In [17]:
y_pred = rf.predict(X_val)

In [18]:
y_pred

array([27.81, 28.31, 31.85, ..., 29.16, 29.12, 32.1 ], shape=(2000,))

In [19]:
rmse = root_mean_squared_error(y_val, y_pred)
rmse

1.8393827905033797

## Question 3

In [20]:
estimators = [10, 50, 100, 150]
scores = []

for n in estimators:
    rf = RandomForestRegressor(n_estimators=n, random_state=1,n_jobs=-1)
    rf.fit(X_train, y_train)

    y_pred = rf.predict(X_val)
    rmse = root_mean_squared_error(y_val, y_pred)
    scores.append((n, rmse))

In [21]:
scores

[(10, 1.8393827905033797),
 (50, 1.7728631357214237),
 (100, 1.7676431541745072),
 (150, 1.768109448598198)]

## Question 4

In [22]:
estimators = [10, 50, 100, 150]
scores = []
max_depths = [10, 15, 20, 25]
for md in max_depths:
    for n in estimators:
        rf = RandomForestRegressor(max_depth=md,n_estimators=n, random_state=1,n_jobs=-1)
        rf.fit(X_train, y_train)
    
        y_pred = rf.predict(X_val)
        rmse = root_mean_squared_error(y_val, y_pred)
        scores.append((md,n, rmse))

In [23]:
scores

[(10, 10, 1.7820961824304398),
 (10, 50, 1.7470902075299413),
 (10, 100, 1.7435552997215298),
 (10, 150, 1.7437904052063802),
 (15, 10, 1.829661865928944),
 (15, 50, 1.771177441028383),
 (15, 100, 1.7672297429312616),
 (15, 150, 1.766612105491821),
 (20, 10, 1.840029279522714),
 (20, 50, 1.7744174965456456),
 (20, 100, 1.7691592763835085),
 (20, 150, 1.767779858169317),
 (25, 10, 1.840010602012993),
 (25, 50, 1.7726834559244737),
 (25, 100, 1.7667317550496155),
 (25, 150, 1.7672723956802336)]

In [24]:
results = pd.DataFrame(scores, columns=["max_depth", "n_estimators", "rmse"])
mean_rmse = results.groupby("max_depth")["rmse"].mean()
print(mean_rmse)

max_depth
10    1.754133
15    1.783670
20    1.787846
25    1.786675
Name: rmse, dtype: float64

## Question 5

In [25]:
rf = RandomForestRegressor(max_depth=20, n_estimators=10, random_state=1,n_jobs=-1)
rf.fit(X_train, y_train)

RandomForestRegressor(max_depth=20, n_estimators=10, n_jobs=-1, random_state=1)

In [26]:
model_importances = rf.feature_importances_

In [27]:
model_importances

array([0.05534153, 0.00797122, 0.02010786, 0.00557414, 0.06115154,
       0.01804496, 0.16071248, 0.01483121, 0.07846831, 0.29591522,
       0.00722733, 0.01936444, 0.00638824, 0.00356628, 0.04226824,
       0.20306701])

In [28]:
print("Generated Features:", dv.get_feature_names_out())

Generated Features: ['acceleration' 'drivetrain=All-wheel drive'
 'drivetrain=Front-wheel drive' 'drivetrain=Rear-wheel drive'
 'engine_displacement' 'fuel_type=Diesel' 'fuel_type=Gasoline'
 'fuel_type=Hybrid' 'horsepower' 'model_year' 'num_cylinders' 'num_doors'
 'origin=Asia' 'origin=Europe' 'origin=USA' 'vehicle_weight']

In [29]:
importances = pd.Series(
    rf.feature_importances_,
    index=dv.get_feature_names_out()
)

importances.sort_values(ascending=False)

model_year                      0.295915
vehicle_weight                  0.203067
fuel_type=Gasoline              0.160712
horsepower                      0.078468
engine_displacement             0.061152
acceleration                    0.055342
origin=USA                      0.042268
drivetrain=Front-wheel drive    0.020108
num_doors                       0.019364
fuel_type=Diesel                0.018045
fuel_type=Hybrid                0.014831
drivetrain=All-wheel drive      0.007971
num_cylinders                   0.007227
origin=Asia                     0.006388
drivetrain=Rear-wheel drive     0.005574
origin=Europe                   0.003566
dtype: float64

## Question 6

In [30]:
features = list(dv.get_feature_names_out())
dtrain = xgb.DMatrix(X_train, label=y_train, feature_names=features)
dval = xgb.DMatrix(X_val, label=y_val, feature_names=features)

In [31]:
watchlist = [(dtrain, 'train'), (dval, 'val')]

In [32]:
scores_xgboost = {}

In [33]:
evaluation_history = {}

In [34]:
def parse_xgb_output(output):
    results = []

    for line in output.stdout.strip().split('\n'):
        it_line, train_line, val_line = line.split('\t')

        it = int(it_line.strip('[]'))
        train = float(train_line.split(':')[1])
        val = float(val_line.split(':')[1])

        results.append((it, train, val))

    columns = ['num_iter', 'train_rmse', 'val_rmse']
    df_results = pd.DataFrame(results, columns=columns)
    return df_results

In [35]:
%%capture output

xgb_params = {
    'eta': 0.3, 
    'max_depth': 6,
    'min_child_weight': 1,
    
    'objective': 'reg:squarederror',
    'nthread': 8,
    'eval_metric': 'rmse',
    'seed': 1,
    'verbosity': 1,
}

model = xgb.train(xgb_params, dtrain, num_boost_round=100,
                  verbose_eval=5,
                  evals=watchlist,
                  evals_result=evaluation_history)

In [36]:
evals_result_1 = parse_xgb_output(output)

In [37]:
%%capture output

xgb_params = {
    'eta': 0.1, 
    'max_depth': 6,
    'min_child_weight': 1,
    
    'objective': 'reg:squarederror',
    'nthread': 8,
    'eval_metric': 'rmse',
    'seed': 1,
    'verbosity': 1,
}

model = xgb.train(xgb_params, dtrain, num_boost_round=100,
                  verbose_eval=5,
                  evals=watchlist,
                  evals_result=evaluation_history)

In [38]:
evals_result_2 = parse_xgb_output(output)

In [39]:
evals_result_1

    num_iter  train_rmse  val_rmse
0          0     2.40653   2.46782
1          5     1.59328   1.76216
2         10     1.47125   1.73205
3         15     1.41908   1.73512
4         20     1.39368   1.73766
5         25     1.35837   1.74359
6         30     1.33243   1.74548
7         35     1.29290   1.75198
8         40     1.25326   1.76296
9         45     1.21527   1.77244
10        50     1.18645   1.77517
11        55     1.14797   1.78668
12        60     1.10265   1.79401
13        65     1.06590   1.80143
14        70     1.04604   1.80444
15        75     1.02727   1.80682
16        80     0.99487   1.81308
17        85     0.96970   1.81600
18        90     0.94986   1.82135
19        95     0.91805   1.82544
20        99     0.90106   1.82646

In [40]:
evals_result_2

    num_iter  train_rmse  val_rmse
0          0     2.74739   2.78635
1          5     2.12109   2.20428
2         10     1.80592   1.93152
3         15     1.64286   1.80346
4         20     1.55847   1.75076
5         25     1.50918   1.72751
6         30     1.47544   1.71667
7         35     1.44978   1.71287
8         40     1.43074   1.71289
9         45     1.41543   1.71310
10        50     1.40368   1.71358
11        55     1.39009   1.71570
12        60     1.37884   1.71688
13        65     1.37172   1.71812
14        70     1.36283   1.71919
15        75     1.35099   1.72057
16        80     1.34578   1.72100
17        85     1.33480   1.72192
18        90     1.32546   1.72303
19        95     1.32292   1.72324
20        99     1.31192   1.72481